// flow-typed signature: dff5b8d574589e115dc9e4f63723094a
// flow-typed version: <<STUB>>/react-swipeable-views_v^0.7.9/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-swipeable-views'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-swipeable-views' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-swipeable-views/lib/autoPlay' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/lib/bindKeyboard' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/lib/constant' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/lib/index' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/lib/index.native.animated' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/lib/index.native.scroll' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/lib/SwipeableViews' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/lib/utils/checkIndexBounds' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/lib/utils/computeIndex' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/lib/utils/getDisplaySameSlide' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/lib/utils/mod' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/lib/virtualize' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/autoPlay' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/bindKeyboard' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/constant' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/index' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/index.native.animated' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/index.native.scroll' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/SwipeableViews' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/utils/checkIndexBounds' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/utils/computeIndex' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/utils/getDisplaySameSlide' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/utils/mod' {
  declare module.exports: any;
}

declare module 'react-swipeable-views/src/virtualize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-swipeable-views/lib/autoPlay.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/autoPlay'>;
}
declare module 'react-swipeable-views/lib/bindKeyboard.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/bindKeyboard'>;
}
declare module 'react-swipeable-views/lib/constant.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/constant'>;
}
declare module 'react-swipeable-views/lib/index.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/index'>;
}
declare module 'react-swipeable-views/lib/index.native.animated.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/index.native.animated'>;
}
declare module 'react-swipeable-views/lib/index.native.scroll.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/index.native.scroll'>;
}
declare module 'react-swipeable-views/lib/SwipeableViews.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/SwipeableViews'>;
}
declare module 'react-swipeable-views/lib/utils/checkIndexBounds.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/utils/checkIndexBounds'>;
}
declare module 'react-swipeable-views/lib/utils/computeIndex.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/utils/computeIndex'>;
}
declare module 'react-swipeable-views/lib/utils/getDisplaySameSlide.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/utils/getDisplaySameSlide'>;
}
declare module 'react-swipeable-views/lib/utils/mod.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/utils/mod'>;
}
declare module 'react-swipeable-views/lib/virtualize.js' {
  declare module.exports: $Exports<'react-swipeable-views/lib/virtualize'>;
}
declare module 'react-swipeable-views/src/autoPlay.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/autoPlay'>;
}
declare module 'react-swipeable-views/src/bindKeyboard.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/bindKeyboard'>;
}
declare module 'react-swipeable-views/src/constant.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/constant'>;
}
declare module 'react-swipeable-views/src/index.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/index'>;
}
declare module 'react-swipeable-views/src/index.native.animated.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/index.native.animated'>;
}
declare module 'react-swipeable-views/src/index.native.scroll.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/index.native.scroll'>;
}
declare module 'react-swipeable-views/src/SwipeableViews.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/SwipeableViews'>;
}
declare module 'react-swipeable-views/src/utils/checkIndexBounds.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/utils/checkIndexBounds'>;
}
declare module 'react-swipeable-views/src/utils/computeIndex.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/utils/computeIndex'>;
}
declare module 'react-swipeable-views/src/utils/getDisplaySameSlide.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/utils/getDisplaySameSlide'>;
}
declare module 'react-swipeable-views/src/utils/mod.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/utils/mod'>;
}
declare module 'react-swipeable-views/src/virtualize.js' {
  declare module.exports: $Exports<'react-swipeable-views/src/virtualize'>;
}
