// flow-typed signature: 87e5f9e19e184f46ed9b78ee81eec180
// flow-typed version: <<STUB>>/react-rating_v^0.5.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-rating'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-rating' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-rating/lib/react-rating' {
  declare module.exports: any;
}

declare module 'react-rating/lib/react-rating.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-rating/lib/react-rating.js' {
  declare module.exports: $Exports<'react-rating/lib/react-rating'>;
}
declare module 'react-rating/lib/react-rating.min.js' {
  declare module.exports: $Exports<'react-rating/lib/react-rating.min'>;
}
