// flow-typed signature: 3767c63f07426a0ffbdc70f79077a8dd
// flow-typed version: <<STUB>>/rebound_v0.0.13/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rebound'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rebound' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rebound/browser_test/jasmine-1.3.1' {
  declare module.exports: any;
}

declare module 'rebound/browser_test/jasmine-html' {
  declare module.exports: any;
}

declare module 'rebound/examples/cascadeEffect/main' {
  declare module.exports: any;
}

declare module 'rebound/examples/hamburgerButton/main' {
  declare module.exports: any;
}

declare module 'rebound/examples/photoScale/main' {
  declare module.exports: any;
}

declare module 'rebound/examples/util' {
  declare module.exports: any;
}

declare module 'rebound/rebound' {
  declare module.exports: any;
}

declare module 'rebound/rebound.min' {
  declare module.exports: any;
}

declare module 'rebound/spec/reboundSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rebound/browser_test/jasmine-1.3.1.js' {
  declare module.exports: $Exports<'rebound/browser_test/jasmine-1.3.1'>;
}
declare module 'rebound/browser_test/jasmine-html.js' {
  declare module.exports: $Exports<'rebound/browser_test/jasmine-html'>;
}
declare module 'rebound/examples/cascadeEffect/main.js' {
  declare module.exports: $Exports<'rebound/examples/cascadeEffect/main'>;
}
declare module 'rebound/examples/hamburgerButton/main.js' {
  declare module.exports: $Exports<'rebound/examples/hamburgerButton/main'>;
}
declare module 'rebound/examples/photoScale/main.js' {
  declare module.exports: $Exports<'rebound/examples/photoScale/main'>;
}
declare module 'rebound/examples/util.js' {
  declare module.exports: $Exports<'rebound/examples/util'>;
}
declare module 'rebound/rebound.js' {
  declare module.exports: $Exports<'rebound/rebound'>;
}
declare module 'rebound/rebound.min.js' {
  declare module.exports: $Exports<'rebound/rebound.min'>;
}
declare module 'rebound/spec/reboundSpec.js' {
  declare module.exports: $Exports<'rebound/spec/reboundSpec'>;
}
