// flow-typed signature: 603ceed66701a570c27941f3aabc18d3
// flow-typed version: <<STUB>>/storybook-readme_v^1.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-readme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-readme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-readme/components/markdown' {
  declare module.exports: any;
}

declare module 'storybook-readme/components/readme-container' {
  declare module.exports: any;
}

declare module 'storybook-readme/components/readme-panel' {
  declare module.exports: any;
}

declare module 'storybook-readme/constants' {
  declare module.exports: any;
}

declare module 'storybook-readme/example/components/button/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/example/components/colored-button/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/example/components/header/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/example/stories/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/readme-manager' {
  declare module.exports: any;
}

declare module 'storybook-readme/register' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/components/markdown' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/components/readme-container' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/components/readme-panel' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/constants' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/readme-manager' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/register' {
  declare module.exports: any;
}

declare module 'storybook-readme/src/with-readme' {
  declare module.exports: any;
}

declare module 'storybook-readme/with-readme' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-readme/components/markdown.js' {
  declare module.exports: $Exports<'storybook-readme/components/markdown'>;
}
declare module 'storybook-readme/components/readme-container.js' {
  declare module.exports: $Exports<'storybook-readme/components/readme-container'>;
}
declare module 'storybook-readme/components/readme-panel.js' {
  declare module.exports: $Exports<'storybook-readme/components/readme-panel'>;
}
declare module 'storybook-readme/constants.js' {
  declare module.exports: $Exports<'storybook-readme/constants'>;
}
declare module 'storybook-readme/example/components/button/index.js' {
  declare module.exports: $Exports<'storybook-readme/example/components/button/index'>;
}
declare module 'storybook-readme/example/components/colored-button/index.js' {
  declare module.exports: $Exports<'storybook-readme/example/components/colored-button/index'>;
}
declare module 'storybook-readme/example/components/header/index.js' {
  declare module.exports: $Exports<'storybook-readme/example/components/header/index'>;
}
declare module 'storybook-readme/example/stories/index.js' {
  declare module.exports: $Exports<'storybook-readme/example/stories/index'>;
}
declare module 'storybook-readme/readme-manager.js' {
  declare module.exports: $Exports<'storybook-readme/readme-manager'>;
}
declare module 'storybook-readme/register.js' {
  declare module.exports: $Exports<'storybook-readme/register'>;
}
declare module 'storybook-readme/src/components/markdown.js' {
  declare module.exports: $Exports<'storybook-readme/src/components/markdown'>;
}
declare module 'storybook-readme/src/components/readme-container.js' {
  declare module.exports: $Exports<'storybook-readme/src/components/readme-container'>;
}
declare module 'storybook-readme/src/components/readme-panel.js' {
  declare module.exports: $Exports<'storybook-readme/src/components/readme-panel'>;
}
declare module 'storybook-readme/src/constants.js' {
  declare module.exports: $Exports<'storybook-readme/src/constants'>;
}
declare module 'storybook-readme/src/readme-manager.js' {
  declare module.exports: $Exports<'storybook-readme/src/readme-manager'>;
}
declare module 'storybook-readme/src/register.js' {
  declare module.exports: $Exports<'storybook-readme/src/register'>;
}
declare module 'storybook-readme/src/with-readme.js' {
  declare module.exports: $Exports<'storybook-readme/src/with-readme'>;
}
declare module 'storybook-readme/with-readme.js' {
  declare module.exports: $Exports<'storybook-readme/with-readme'>;
}
